export const furnitures = [
  {
    category: "baños",
    type: "baño",
    url: "/assets/imgs-trabajos/baños/baño-1.webp",
    wood: "encino",
    color: "chocolate",
  },
  {
    category: "baños",
    type: "baño",
    url: "/assets/imgs-trabajos/baños/baño-2.webp",
    wood: "tzalam",
    color: "cedro",
  },
  {
    category: "baños",
    type: "baño",
    url: "/assets/imgs-trabajos/baños/baño-3.webp",
    wood: "mdf",
    color: "amarillo",
  },
  {
    category: "baños",
    type: "baño",
    url: "/assets/imgs-trabajos/baños/baño-4.webp",
    wood: "cedro",
    color: "natural",
  },
  {
    category: "baños",
    type: "baño",
    url: "/assets/imgs-trabajos/baños/baño-5.webp",
    wood: "caobilla",
    color: "nogal",
  },
  {
    category: "baños",
    type: "baño",
    url: "/assets/imgs-trabajos/baños/baño-6.webp",
    wood: "tzalam",
    color: "natural",
  },
  {
    category: "baños",
    type: "baño",
    url: "/assets/imgs-trabajos/baños/baño-7.webp",
    wood: "prensado",
    color: "natural",
  },
  {
    category: "baños",
    type: "baño",
    url: "/assets/imgs-trabajos/baños/baño-8.webp",
    wood: "parota",
    color: "natural",
  },

  {
    category: "credenzas",
    type: "credenza",
    url: "/assets/imgs-trabajos/credenzas/credenza-1.webp",
    wood: "caobilla",
    color: "nogal",
  },
  {
    category: "credenzas",
    type: "credenza",
    url: "/assets/imgs-trabajos/credenzas/credenza-2.webp",
    wood: "listonado",
    color: "arena",
  },
  {
    category: "credenzas",
    type: "credenza",
    url: "/assets/imgs-trabajos/credenzas/credenza-3.webp",
    wood: "tzalam",
    color: "natural",
  },
  {
    category: "credenzas",
    type: "credenza",
    url: "/assets/imgs-trabajos/credenzas/credenza-4.webp",
    wood: "listonado",
    color: "nogal oscuro",
  },
  {
    category: "credenzas",
    type: "credenza",
    url: "/assets/imgs-trabajos/credenzas/credenza-5.webp",
    wood: "caobilla",
    color: "chocolate oscuro",
  },
  {
    category: "credenzas",
    type: "credenza",
    url: "/assets/imgs-trabajos/credenzas/credenza-6.webp",
    wood: "tzalam",
    color: "natural",
  },
  {
    category: "credenzas",
    type: "credenza",
    url: "/assets/imgs-trabajos/credenzas/credenza-7.webp",
    wood: "caobilla",
    color: "nogal",
  },
  {
    category: "credenzas",
    type: "credenza",
    url: "/assets/imgs-trabajos/credenzas/credenza-8.webp",
    wood: "listonado",
    color: "caoba",
  },
  {
    category: "recamara",
    type: "cama",
    url: "/assets/imgs-trabajos/camas/cama-1.webp",
    wood: "pino",
    color: "chocolate",
  },
  {
    category: "recamara",
    type: "cama",
    url: "/assets/imgs-trabajos/camas/cama-2.webp",
    wood: "listonado",
    color: "nogal",
  },
  {
    category: "recamara",
    type: "cama",
    url: "/assets/imgs-trabajos/camas/cama-3.webp",
    wood: "listonado",
    color: "blanco",
  },
  {
    category: "recamara",
    type: "cama",
    url: "/assets/imgs-trabajos/camas/cama-4.webp",
    wood: "pino",
    color: "blanco",
  },
  {
    category: "recamara",
    type: "cama",
    url: "/assets/imgs-trabajos/camas/cama-5.webp",
    wood: "parota",
    color: "natural",
  },
  {
    category: "recamara",
    type: "cama",
    url: "/assets/imgs-trabajos/camas/cama-6.webp",
    wood: "cedro",
    color: "nogal",
  },
  {
    category: "recamara",
    type: "cama",
    url: "/assets/imgs-trabajos/camas/cama-7.webp",
    wood: "caobilla",
    color: "chocolate",
  },
  {
    category: "recamara",
    type: "cama",
    url: "/assets/imgs-trabajos/camas/cama-8.webp",
    wood: "tzalam",
    color: "nogal",
  },
  {
    category: "recamara",
    type: "cama",
    url: "/assets/imgs-trabajos/camas/cama-9.webp",
    wood: "tzalam",
    color: "natural",
  },
  {
    category: "recamara",
    type: "closet",
    url: "/assets/imgs-trabajos/closets/closet-1.webp",
    wood: "caobilla",
    color: "nogal",
  },
  {
    category: "recamara",
    type: "closet",
    url: "/assets/imgs-trabajos/closets/closet-2.webp",
    wood: "tzalam",
    color: "natural",
  },
  {
    category: "recamara",
    type: "closet",
    url: "/assets/imgs-trabajos/closets/closet-3.webp",
    wood: "caobilla",
    color: "oyamel",
  },
  {
    category: "recamara",
    type: "closet",
    url: "/assets/imgs-trabajos/closets/closet-4.webp",
    wood: "caobilla",
    color: "oyamel",
  },
  {
    category: "recamara",
    type: "closet",
    url: "/assets/imgs-trabajos/closets/closet-5.webp",
    wood: "caobilla",
    color: "nogal",
  },
  {
    category: "recamara",
    type: "closet",
    url: "/assets/imgs-trabajos/closets/closet-6.webp",
    wood: "caobilla",
    color: "caoba",
  },
  {
    category: "recamara",
    type: "closet",
    url: "/assets/imgs-trabajos/closets/closet-7.webp",
    wood: "tzalam",
    color: "natural",
  },
  {
    category: "recamara",
    type: "closet",
    url: "/assets/imgs-trabajos/closets/closet-8.webp",
    wood: "caobilla",
    color: "chocolate",
  },
  {
    category: "recamara",
    type: "closet",
    url: "/assets/imgs-trabajos/closets/closet-9.webp",
    wood: "caobilla",
    color: "chocolate",
  },
  {
    category: "recamara",
    type: "closet",
    url: "/assets/imgs-trabajos/closets/closet-10.webp",
    wood: "tzalam",
    color: "natural",
  },
  {
    category: "recamara",
    type: "closet",
    url: "/assets/imgs-trabajos/closets/closet-11.webp",
    wood: "tzalam",
    color: "nogal oscuro",
  },
  {
    category: "recamara",
    type: "closet",
    url: "/assets/imgs-trabajos/closets/closet-12.webp",
    wood: "tzalam",
    color: "olmo",
  },
  {
    category: "recamara",
    type: "closet",
    url: "/assets/imgs-trabajos/closets/closet-13.webp",
    wood: "caobilla",
    color: "nogal oscuro",
  },
  {
    category: "recamara",
    type: "closet",
    url: "/assets/imgs-trabajos/closets/closet-14.webp",
    wood: "encino",
    color: "nogal oscuro",
  },
  {
    category: "recamara",
    type: "closet",
    url: "/assets/imgs-trabajos/closets/closet-15.webp",
    wood: "encino",
    color: "cedro",
  },
  {
    category: "recamara",
    type: "closet",
    url: "/assets/imgs-trabajos/closets/closet-16.webp",
    wood: "tzalam",
    color: "nogal",
  },
  {
    category: "recamara",
    type: "closet",
    url: "/assets/imgs-trabajos/closets/closet-17.webp",
    wood: "encino",
    color: "natural",
  },
  {
    category: "recamara",
    type: "closet",
    url: "/assets/imgs-trabajos/closets/closet-18.webp",
    wood: "caobilla",
    color: "blanco",
  },
  {
    category: "recamara",
    type: "closet",
    url: "/assets/imgs-trabajos/closets/closet-19.webp",
    wood: "tzalam",
    color: "natural",
  },
  {
    category: "recamara",
    type: "closet",
    url: "/assets/imgs-trabajos/closets/closet-20.webp",
    wood: "tzalam",
    color: "natural",
  },
  {
    category: "recamara",
    type: "closet",
    url: "/assets/imgs-trabajos/closets/closet-21.webp",
    wood: "caobilla",
    color: "nogal",
  },
  {
    category: "recamara",
    type: "closet",
    url: "/assets/imgs-trabajos/closets/closet-22.webp",
    wood: "caobilla",
    color: "fresno",
  },
  {
    category: "recamara",
    type: "closet",
    url: "/assets/imgs-trabajos/closets/closet-23.webp",
    wood: "caobilla",
    color: "fresno",
  },
  {
    category: "recamara",
    type: "closet",
    url: "/assets/imgs-trabajos/closets/closet-24.webp",
    wood: "tzalam",
    color: "natural",
  },
  {
    category: "recamara",
    type: "closet",
    url: "/assets/imgs-trabajos/closets/closet-25.webp",
    wood: "mdf",
    color: "amarillo",
  },
  {
    category: "recamara",
    type: "closet",
    url: "/assets/imgs-trabajos/closets/closet-26.webp",
    wood: "caobilla",
    color: "nogal",
  },
  {
    category: "recamara",
    type: "closet",
    url: "/assets/imgs-trabajos/closets/closet-27.webp",
    wood: "caobilla",
    color: "chocolate",
  },
  {
    category: "recamara",
    type: "closet",
    url: "/assets/imgs-trabajos/closets/closet-28.webp",
    wood: "caobilla",
    color: "nogal oscuro",
  },
  {
    category: "recamara",
    type: "closet",
    url: "/assets/imgs-trabajos/closets/closet-29.webp",
    wood: "caobilla",
    color: "caoba",
  },

  {
    category: "comedores",
    type: "comedor",
    url: "/assets/imgs-trabajos/comedores/comedor-1.webp",
    wood: "tzalam",
    color: "natural",
  },
  {
    category: "comedores",
    type: "comedor",
    url: "/assets/imgs-trabajos/comedores/comedor-2.webp",
    wood: "cedro",
    color: "nogal oscuro",
  },
  {
    category: "comedores",
    type: "comedor",
    url: "/assets/imgs-trabajos/comedores/comedor-3.webp",
    wood: "caobilla",
    color: "chocolate",
  },
  {
    category: "comedores",
    type: "comedor",
    url: "/assets/imgs-trabajos/comedores/comedor-4.webp",
    wood: "cedro",
    color: "caoba",
  },
  {
    category: "comedores",
    type: "comedor",
    url: "/assets/imgs-trabajos/comedores/comedor-5.webp",
    wood: "cedro",
    color: "nogal",
  },

  {
    category: "tvs",
    type: "tv",
    url: "/assets/imgs-trabajos/tvs/tv-1.webp",
    wood: "tzalam",
    color: "natural",
  },
  {
    category: "tvs",
    type: "tv",
    url: "/assets/imgs-trabajos/tvs/tv-2.webp",
    wood: "caobilla",
    color: "nogal",
  },
  {
    category: "tvs",
    type: "tv",
    url: "/assets/imgs-trabajos/tvs/tv-3.webp",
    wood: "cedro",
    color: "natural",
  },
  {
    category: "tvs",
    type: "tv",
    url: "/assets/imgs-trabajos/tvs/tv-4.webp",
    wood: "encino",
    color: "natural",
  },
  {
    category: "tvs",
    type: "tv",
    url: "/assets/imgs-trabajos/tvs/tv-5.webp",
    wood: "caobilla",
    color: "nogal",
  },
  {
    category: "tvs",
    type: "tv",
    url: "/assets/imgs-trabajos/tvs/tv-6.webp",
    wood: "caobilla",
    color: "caoba",
  },
  {
    category: "tvs",
    type: "tv",
    url: "/assets/imgs-trabajos/tvs/tv-7.webp",
    wood: "caobilla",
    color: "nogal oscuro",
  },
  {
    category: "tvs",
    type: "tv",
    url: "/assets/imgs-trabajos/tvs/tv-8.webp",
    wood: "tzalam",
    color: "caoba",
  },
  {
    category: "tvs",
    type: "tv",
    url: "/assets/imgs-trabajos/tvs/tv-9.webp",
    wood: "prensado",
    color: "natural",
  },

  {
    category: "oficina",
    type: "escritorio",
    url: "/assets/imgs-trabajos/escritorios/escritorio-1.webp",
    wood: "caobilla",
    color: "nogal y blanco",
  },
  {
    category: "oficina",
    type: "escritorio",
    url: "/assets/imgs-trabajos/escritorios/escritorio-2.webp",
    wood: "caobilla",
    color: "chocolate",
  },
  {
    category: "oficina",
    type: "escritorio",
    url: "/assets/imgs-trabajos/escritorios/escritorio-3.webp",
    wood: "caobilla",
    color: "nogal",
  },
  {
    category: "oficina",
    type: "escritorio",
    url: "/assets/imgs-trabajos/escritorios/escritorio-4.webp",
    wood: "caobilla",
    color: "nogal",
  },
  {
    category: "oficina",
    type: "escritorio",
    url: "/assets/imgs-trabajos/escritorios/escritorio-5.webp",
    wood: "encino",
    color: "nogal",
  },
  {
    category: "oficina",
    type: "escritorio",
    url: "/assets/imgs-trabajos/escritorios/escritorio-6.webp",
    wood: "parota",
    color: "natural",
  },
  {
    category: "oficina",
    type: "escritorio",
    url: "/assets/imgs-trabajos/escritorios/escritorio-7.webp",
    wood: "caobilla",
    color: "negro y caoba",
  },
  {
    category: "oficina",
    type: "escritorio",
    url: "/assets/imgs-trabajos/escritorios/escritorio-8.webp",
    wood: "cedro",
    color: "maple",
  },
  {
    category: "oficina",
    type: "escritorio",
    url: "/assets/imgs-trabajos/escritorios/escritorio-9.webp",
    wood: "caobilla",
    color: "nogal",
  },
  {
    category: "oficina",
    type: "librero",
    url: "/assets/imgs-trabajos/libreros/librero-1.webp",
    wood: "caobilla",
    color: "negro",
  },
  {
    category: "oficina",
    type: "librero",
    url: "/assets/imgs-trabajos/libreros/librero-2.webp",
    wood: "caobilla",
    color: "nogal",
  },
  {
    category: "oficina",
    type: "librero",
    url: "/assets/imgs-trabajos/libreros/librero-3.webp",
    wood: "caobilla",
    color: "nogal oscuro",
  },

  {
    category: "puertas",
    type: "puerta",
    url: "/assets/imgs-trabajos/puertas/puerta-1.webp",
    wood: "cedro",
    color: "natural",
  },
  {
    category: "puertas",
    type: "puerta",
    url: "/assets/imgs-trabajos/puertas/puerta-2.webp",
    wood: "caobilla",
    color: "negro",
  },
  {
    category: "puertas",
    type: "puerta",
    url: "/assets/imgs-trabajos/puertas/puerta-3.webp",
    wood: "cedro",
    color: "negro",
  },
  {
    category: "puertas",
    type: "puerta",
    url: "/assets/imgs-trabajos/puertas/puerta-4.webp",
    wood: "cedro",
    color: "caoba",
  },
  {
    category: "puertas",
    type: "puerta",
    url: "/assets/imgs-trabajos/puertas/puerta-5.webp",
    wood: "caobilla",
    color: "blanco",
  },
  {
    category: "puertas",
    type: "puerta",
    url: "/assets/imgs-trabajos/puertas/puerta-6.webp",
    wood: "cedro",
    color: "negro",
  },
  {
    category: "puertas",
    type: "puerta",
    url: "/assets/imgs-trabajos/puertas/puerta-7.webp",
    wood: "cedro",
    color: "nogal",
  },
  {
    category: "puertas",
    type: "puerta",
    url: "/assets/imgs-trabajos/puertas/puerta-8.webp",
    wood: "cedro",
    color: "nogal oscuro",
  },
  {
    category: "puertas",
    type: "puerta",
    url: "/assets/imgs-trabajos/puertas/puerta-9.webp",
    wood: "tzalam",
    color: "nogal",
  },
  {
    category: "puertas",
    type: "puerta",
    url: "/assets/imgs-trabajos/puertas/puerta-10.webp",
    wood: "parota",
    color: "nogal",
  },
  {
    category: "puertas",
    type: "puerta",
    url: "/assets/imgs-trabajos/puertas/puerta-11.webp",
    wood: "cedro",
    color: "blanco",
  },
  {
    category: "puertas",
    type: "puerta",
    url: "/assets/imgs-trabajos/puertas/puerta-12.webp",
    wood: "cedro",
    color: "natural",
  },
  {
    category: "puertas",
    type: "puerta",
    url: "/assets/imgs-trabajos/puertas/puerta-13.webp",
    wood: "encino",
    color: "nogal",
  },
  {
    category: "puertas",
    type: "puerta",
    url: "/assets/imgs-trabajos/puertas/puerta-14.webp",
    wood: "tzalam",
    color: "nogal",
  },
  {
    category: "puertas",
    type: "puerta",
    url: "/assets/imgs-trabajos/puertas/puerta-15.webp",
    wood: "cedro",
    color: "nogal",
  },
  {
    category: "puertas",
    type: "puerta",
    url: "/assets/imgs-trabajos/puertas/puerta-16.webp",
    wood: "cedro",
    color: "nogal",
  },
  {
    category: "puertas",
    type: "puerta",
    url: "/assets/imgs-trabajos/puertas/puerta-17.webp",
    wood: "cedro",
    color: "natural",
  },
  {
    category: "puertas",
    type: "puerta",
    url: "/assets/imgs-trabajos/puertas/puerta-18.webp",
    wood: "tzalam",
    color: "nogal",
  },
  {
    category: "puertas",
    type: "puerta",
    url: "/assets/imgs-trabajos/puertas/puerta-19.webp",
    wood: "cedro",
    color: "nogal",
  },
  {
    category: "puertas",
    type: "puerta",
    url: "/assets/imgs-trabajos/puertas/puerta-20.webp",
    wood: "caobilla",
    color: "fresno",
  },
  {
    category: "puertas",
    type: "puerta",
    url: "/assets/imgs-trabajos/puertas/puerta-21.webp",
    wood: "caobilla",
    color: "nogal",
  },
  {
    category: "puertas",
    type: "puerta",
    url: "/assets/imgs-trabajos/puertas/puerta-22.webp",
    wood: "pino",
    color: "morado claro",
  },
  {
    category: "puertas",
    type: "puerta",
    url: "/assets/imgs-trabajos/puertas/puerta-23.webp",
    wood: "cedro",
    color: "natural",
  },
  {
    category: "puertas",
    type: "puerta",
    url: "/assets/imgs-trabajos/puertas/puerta-24.webp",
    wood: "cedro",
    color: "verde limon",
  },
  {
    category: "puertas",
    type: "puerta",
    url: "/assets/imgs-trabajos/puertas/puerta-25.webp",
    wood: "tzalam",
    color: "oyamel",
  },
  {
    category: "puertas",
    type: "puerta",
    url: "/assets/imgs-trabajos/puertas/puerta-26.webp",
    wood: "caobilla",
    color: "nogal",
  },
  {
    category: "puertas",
    type: "puerta",
    url: "/assets/imgs-trabajos/puertas/puerta-27.webp",
    wood: "cedro",
    color: "nogal oscuro",
  },
  {
    category: "puertas",
    type: "puerta",
    url: "/assets/imgs-trabajos/puertas/puerta-28.webp",
    wood: "tzalam",
    color: "caoba",
  },
  {
    category: "puertas",
    type: "puerta",
    url: "/assets/imgs-trabajos/puertas/puerta-29.webp",
    wood: "tzalam",
    color: "aqua",
  },
  {
    category: "puertas",
    type: "puerta",
    url: "/assets/imgs-trabajos/puertas/puerta-30.webp",
    wood: "tzalam",
    color: "caoba",
  },
  {
    category: "puertas",
    type: "puerta",
    url: "/assets/imgs-trabajos/puertas/puerta-31.webp",
    wood: "tzalam",
    color: "nogal oscuro",
  },
  {
    category: "puertas",
    type: "puerta",
    url: "/assets/imgs-trabajos/puertas/puerta-32.webp",
    wood: "tzalam",
    color: "nogal oscuro",
  },
  {
    category: "puertas",
    type: "puerta",
    url: "/assets/imgs-trabajos/puertas/puerta-33.webp",
    wood: "tzalam",
    color: "nogal oscuro",
  },

  {
    category: "cocinas",
    type: "cocina",
    url: "/assets/imgs-trabajos/cocinas/cocina-1.webp",
    wood: "caobilla",
    color: "nogal",
  },
  {
    category: "cocinas",
    type: "cocina",
    url: "/assets/imgs-trabajos/cocinas/cocina-2.webp",
    wood: "tzalam",
    color: "natural",
  },
  {
    category: "cocinas",
    type: "cocina",
    url: "/assets/imgs-trabajos/cocinas/cocina-3.webp",
    wood: "mdf",
    color: "naranja",
  },
  {
    category: "cocinas",
    type: "cocina",
    url: "/assets/imgs-trabajos/cocinas/cocina-4.webp",
    wood: "pino",
    color: "nogal",
  },
  {
    category: "cocinas",
    type: "cocina",
    url: "/assets/imgs-trabajos/cocinas/cocina-5.webp",
    wood: "mdf",
    color: "nogal oscuro",
  },
  {
    category: "cocinas",
    type: "cocina",
    url: "/assets/imgs-trabajos/cocinas/cocina-6.webp",
    wood: "listonado",
    color: "nogal",
  },
  {
    category: "cocinas",
    type: "cocina",
    url: "/assets/imgs-trabajos/cocinas/cocina-7.webp",
    wood: "caobilla",
    color: "chocolate",
  },
  {
    category: "cocinas",
    type: "cocina",
    url: "/assets/imgs-trabajos/cocinas/cocina-8.webp",
    wood: "listonado",
    color: "nogal",
  },
  {
    category: "cocinas",
    type: "cocina",
    url: "/assets/imgs-trabajos/cocinas/cocina-9.webp",
    wood: "listonado",
    color: "nogal",
  },
  {
    category: "cocinas",
    type: "cocina",
    url: "/assets/imgs-trabajos/cocinas/cocina-10.webp",
    wood: "listonado",
    color: "oyamel",
  },
  {
    category: "cocinas",
    type: "cocina",
    url: "/assets/imgs-trabajos/cocinas/cocina-11.webp",
    wood: "listonado",
    color: "nogal",
  },
  {
    category: "cocinas",
    type: "cocina",
    url: "/assets/imgs-trabajos/cocinas/cocina-12.webp",
    wood: "listonado",
    color: "fresno",
  },
  {
    category: "cocinas",
    type: "cocina",
    url: "/assets/imgs-trabajos/cocinas/cocina-13.webp",
    wood: "listonado",
    color: "fresno",
  },
  {
    category: "cocinas",
    type: "cocina",
    url: "/assets/imgs-trabajos/cocinas/cocina-14.webp",
    wood: "cedro",
    color: "fresno oscuro",
  },
  {
    category: "cocinas",
    type: "cocina",
    url: "/assets/imgs-trabajos/cocinas/cocina-15.webp",
    wood: "cedro",
    color: "fresno oscuro",
  },
  {
    category: "cocinas",
    type: "cocina",
    url: "/assets/imgs-trabajos/cocinas/cocina-16.webp",
    wood: "tzalam",
    color: "natural",
  },
  {
    category: "cocinas",
    type: "cocina",
    url: "/assets/imgs-trabajos/cocinas/cocina-17.webp",
    wood: "encino",
    color: "natural",
  },
  {
    category: "cocinas",
    type: "cocina",
    url: "/assets/imgs-trabajos/cocinas/cocina-18.webp",
    wood: "mdf",
    color: "gris",
  },
  {
    category: "cocinas",
    type: "cocina",
    url: "/assets/imgs-trabajos/cocinas/cocina-19.webp",
    wood: "listonado",
    color: "nogal",
  },
  {
    category: "cocinas",
    type: "cocina",
    url: "/assets/imgs-trabajos/cocinas/cocina-20.webp",
    wood: "mdf",
    color: "rojo",
  },
  {
    category: "cocinas",
    type: "cocina",
    url: "/assets/imgs-trabajos/cocinas/cocina-21.webp",
    wood: "listonado",
    color: "caoba",
  },
  {
    category: "cocinas",
    type: "cocina",
    url: "/assets/imgs-trabajos/cocinas/cocina-22.webp",
    wood: "mdf",
    color: "blanco",
  },
  {
    category: "cocinas",
    type: "cocina",
    url: "/assets/imgs-trabajos/cocinas/cocina-23.webp",
    wood: "pino",
    color: "blanco",
  },
  {
    category: "cocinas",
    type: "cocina",
    url: "/assets/imgs-trabajos/cocinas/cocina-24.webp",
    wood: "tzalam",
    color: "natural",
  },
  {
    category: "cocinas",
    type: "cocina",
    url: "/assets/imgs-trabajos/cocinas/cocina-25.webp",
    wood: "listonado",
    color: "blanco",
  },
  {
    category: "cocinas",
    type: "cocina",
    url: "/assets/imgs-trabajos/cocinas/cocina-26.webp",
    wood: "cedro",
    color: "caoba",
  },
  {
    category: "cocinas",
    type: "cocina",
    url: "/assets/imgs-trabajos/cocinas/cocina-27.webp",
    wood: "cedro",
    color: "verde limon",
  },
  {
    category: "cocinas",
    type: "cocina",
    url: "/assets/imgs-trabajos/cocinas/cocina-28.webp",
    wood: "cedro",
    color: "verde limon",
  },
  {
    category: "cocinas",
    type: "cocina",
    url: "/assets/imgs-trabajos/cocinas/cocina-29.webp",
    wood: "cedro",
    color: "verde limon",
  },
  {
    category: "cocinas",
    type: "cocina",
    url: "/assets/imgs-trabajos/cocinas/cocina-30.webp",
    wood: "caobilla",
    color: "nogal oscuro",
  },
  {
    category: "cocinas",
    type: "cocina",
    url: "/assets/imgs-trabajos/cocinas/cocina-31.webp",
    wood: "tzalam",
    color: "nogal oscuro",
  },
  {
    category: "cocinas",
    type: "cocina",
    url: "/assets/imgs-trabajos/cocinas/cocina-32.webp",
    wood: "caobilla",
    color: "azul oscuro",
  },
  {
    category: "cocinas",
    type: "cocina",
    url: "/assets/imgs-trabajos/cocinas/cocina-33.webp",
    wood: "caobilla",
    color: "azul oscuro",
  },

  {
    category: "cocinas",
    type: "cocina",
    url: "/assets/imgs-trabajos/cocinas/cocina-34.webp",
    wood: "caobilla",
    color: "caoba",
  },
  {
    category: "cocinas",
    type: "cocina",
    url: "/assets/imgs-trabajos/cocinas/cocina-35.webp",
    wood: "tzalam",
    color: "nogal oscuro",
  },
  {
    category: "cocinas",
    type: "cocina",
    url: "/assets/imgs-trabajos/cocinas/cocina-36.webp",
    wood: "caobilla",
    color: "fresno oscuro",
  },

  {
    category: "especiales",
    type: "tocador",
    url: "/assets/imgs-trabajos/especiales/especial-1.webp",
    wood: "caobilla",
    color: "nogal",
  },
  {
    category: "especiales",
    type: "librero",
    url: "/assets/imgs-trabajos/especiales/especial-2.webp",
    wood: "cedro",
    color: "natural",
  },
  {
    category: "especiales",
    type: "cajonera",
    url: "/assets/imgs-trabajos/especiales/especial-3.webp",
    wood: "cedro",
    color: "natural",
  },
  {
    category: "especiales",
    type: "separador",
    url: "/assets/imgs-trabajos/especiales/especial-4.webp",
    wood: "encino",
    color: "natural",
  },
  {
    category: "especiales",
    type: "sala de reunion",
    url: "/assets/imgs-trabajos/especiales/especial-5.webp",
    wood: "cedro",
    color: "caoba y negro",
  },
  {
    category: "especiales",
    type: "alacena",
    url: "/assets/imgs-trabajos/especiales/especial-6.webp",
    wood: "encino",
    color: "alamo",
  },
  {
    category: "especiales",
    type: "divisor",
    url: "/assets/imgs-trabajos/especiales/especial-7.webp",
    wood: "caobilla",
    color: "cedro",
  },
  {
    category: "especiales",
    type: "cajonera",
    url: "/assets/imgs-trabajos/especiales/especial-8.webp",
    wood: "tzalam",
    color: "okume",
  },
  {
    category: "especiales",
    type: "barandal",
    url: "/assets/imgs-trabajos/especiales/especial-9.webp",
    wood: "cedro",
    color: "nogal oscuro",
  },
  {
    category: "especiales",
    type: "banco",
    url: "/assets/imgs-trabajos/especiales/especial-10.webp",
    wood: "pino",
    color: "nogal",
  },
  {
    category: "especiales",
    type: "sala",
    url: "/assets/imgs-trabajos/especiales/especial-11.webp",
    wood: "tzalam",
    color: "natural",
  },
  {
    category: "especiales",
    type: "muro",
    url: "/assets/imgs-trabajos/especiales/especial-12.webp",
    wood: "pino",
    color: "nogal",
  },
  {
    category: "especiales",
    type: "camino",
    url: "/assets/imgs-trabajos/especiales/especial-13.webp",
    wood: "parota",
    color: "natural",
  },
  {
    category: "especiales",
    type: "cajonera",
    url: "/assets/imgs-trabajos/especiales/especial-14.webp",
    wood: "pino",
    color: "fresno",
  },
  {
    category: "especiales",
    type: "barandal",
    url: "/assets/imgs-trabajos/especiales/especial-15.webp",
    wood: "cedro",
    color: "caoba",
  },
  {
    category: "especiales",
    type: "barandal",
    url: "/assets/imgs-trabajos/especiales/especial-16.webp",
    wood: "cedro",
    color: "caoba",
  },
  {
    category: "especiales",
    type: "basurero",
    url: "/assets/imgs-trabajos/especiales/especial-17.webp",
    wood: "encino",
    color: "natural",
  },
  {
    category: "especiales",
    type: "vinero",
    url: "/assets/imgs-trabajos/especiales/especial-18.webp",
    wood: "caobilla",
    color: "chocolate",
  },
  {
    category: "especiales",
    type: "podium",
    url: "/assets/imgs-trabajos/especiales/especial-19.webp",
    wood: "cedro",
    color: "oyamel",
  },
  {
    category: "especiales",
    type: "bufetera",
    url: "/assets/imgs-trabajos/especiales/especial-20.webp",
    wood: "parota",
    color: "natural",
  },
  {
    category: "especiales",
    type: "divisor",
    url: "/assets/imgs-trabajos/especiales/especial-21.webp",
    wood: "caobilla",
    color: "nogal",
  },
  {
    category: "especiales",
    type: "duela",
    url: "/assets/imgs-trabajos/especiales/especial-22.webp",
    wood: "pino",
    color: "nogal oscuro",
  },
  {
    category: "especiales",
    type: "repizas",
    url: "/assets/imgs-trabajos/especiales/especial-23.webp",
    wood: "pino",
    color: "nogal",
  },
  {
    category: "especiales",
    type: "mostrador",
    url: "/assets/imgs-trabajos/especiales/especial-24.webp",
    wood: "cedro",
    color: "morado pastel",
  },
  {
    category: "especiales",
    type: "repizas",
    url: "/assets/imgs-trabajos/especiales/especial-25.webp",
    wood: "pino",
    color: "nogal",
  },
  {
    category: "especiales",
    type: "repizas cajonera",
    url: "/assets/imgs-trabajos/especiales/especial-26.webp",
    wood: "caobilla",
    color: "caoba",
  },
  {
    category: "especiales",
    type: "cajonera",
    url: "/assets/imgs-trabajos/especiales/especial-27.webp",
    wood: "caobilla",
    color: "blanco",
  },
  {
    category: "especiales",
    type: "repiza",
    url: "/assets/imgs-trabajos/especiales/especial-28.webp",
    wood: "caobilla",
    color: "chocolate oscuro",
  },
  {
    category: "especiales",
    type: "esquinero",
    url: "/assets/imgs-trabajos/especiales/especial-29.webp",
    wood: "tzalam",
    color: "natural",
  },
  {
    category: "especiales",
    type: "tejaban",
    url: "/assets/imgs-trabajos/especiales/especial-30.webp",
    wood: "parota",
    color: "natural",
  },
  {
    category: "especiales",
    type: "cajonera",
    url: "/assets/imgs-trabajos/especiales/especial-31.webp",
    wood: "pino",
    color: "nogal",
  },
  {
    category: "especiales",
    type: "cajonera",
    url: "/assets/imgs-trabajos/especiales/especial-32.webp",
    wood: "tzalam",
    color: "natural",
  },
  {
    category: "especiales",
    type: "alacena",
    url: "/assets/imgs-trabajos/especiales/especial-33.webp",
    wood: "tzalam",
    color: "nogal",
  },
  {
    category: "especiales",
    type: "sala",
    url: "/assets/imgs-trabajos/especiales/especial-34.webp",
    wood: "tzalam",
    color: "nogal",
  },
  {
    category: "especiales",
    type: "vinero",
    url: "/assets/imgs-trabajos/especiales/especial-35.webp",
    wood: "tzalam",
    color: "nogal",
  },
  {
    category: "especiales",
    type: "mesa de centro",
    url: "/assets/imgs-trabajos/especiales/especial-36.webp",
    wood: "tzalam",
    color: "nogal",
  },
  {
    category: "especiales",
    type: "mesa cajonera",
    url: "/assets/imgs-trabajos/especiales/especial-37.webp",
    wood: "tzalam",
    color: "roble",
  },
  {
    category: "especiales",
    type: "mesa de centro",
    url: "/assets/imgs-trabajos/especiales/especial-38.webp",
    wood: "tzalam",
    color: "oyamel",
  },
  {
    category: "especiales",
    type: "recibidor",
    url: "/assets/imgs-trabajos/especiales/especial-39.webp",
    wood: "caobilla",
    color: "nogal oscuro",
  },
];
