export const furnitures = {
  baños: [
    {
      categoria: "baños",
      foto: "./assets/imgs-trabajos/baños/baño-1.jpg",
      madera: "encino",
      color: "chocolate",
    },
    {
      categoria: "baños",
      foto: "./assets/imgs-trabajos/baños/baño-2.jpg",
      madera: "caobilla",
      color: "cedro",
    },
    {
      categoria: "baños",
      foto: "/assets/imgs-trabajos/baños/baño-3.jpg",
      madera: "mdf",
      color: "otros",
    },
    {
      categoria: "baños",
      foto: "/assets/imgs-trabajos/baños/baño-4.jpg",
      madera: "caobilla",
      color: "cedro",
    },
  ],
  cajoneras: [
    {
      categoria: "cajoneras",
      foto: "/assets/imgs-trabajos/cajoneras/cajonera-1.jpeg",
      madera: "caobilla",
      color: "nogal",
    },
    {
      categoria: "cajoneras",
      foto: "/assets/imgs-trabajos/cajoneras/cajonera-2.jpeg",
      madera: "tzalam",
      color: "nogal",
    },
    {
      categoria: "cajoneras",
      foto: "/assets/imgs-trabajos/cajoneras/cajonera-3.jpeg",
      madera: "caobilla",
      color: "otros",
    },
    {
      categoria: "cajoneras",
      foto: "/assets/imgs-trabajos/cajoneras/cajonera-4.jpeg",
      madera: "parota",
      color: "otros",
    },
    {
      categoria: "cajoneras",
      foto: "/assets/imgs-trabajos/cajoneras/cajonera-5.jpeg",
      madera: "tzalam",
      color: "nogal",
    },
  ],
  camas: [
    {
      categoria: "camas",
      foto: "/assets/imgs-trabajos/camas/cama-1.jpg",
      madera: "pino",
      color: "chocolate",
    },
    {
      categoria: "camas",
      foto: "/assets/imgs-trabajos/camas/cama-2.jpg",
      madera: "tzalam",
      color: "nogal",
    },
    {
      categoria: "camas",
      foto: "/assets/imgs-trabajos/camas/cama-3.jpg",
      madera: "parota",
      color: "natural",
    },
    {
      categoria: "camas",
      foto: "/assets/imgs-trabajos/camas/cama-4.jpeg",
      madera: "pino",
      color: "otros",
    },
    {
      categoria: "camas",
      foto: "/assets/imgs-trabajos/camas/cama-5.jpeg",
      madera: "parota",
      color: "natural",
    },
    {
      categoria: "camas",
      foto: "/assets/imgs-trabajos/camas/cama-6.jpeg",
      madera: "cedro",
      color: "nogal",
    },
    {
      categoria: "camas",
      foto: "/assets/imgs-trabajos/camas/cama-7.jpeg",
      madera: "caobilla",
      color: "chocolate",
    },
  ],
  closets: [
    {
      categoria: "closets",
      foto: "/assets/imgs-trabajos/closets/closet-1.jpeg",
      madera: "caobilla",
      color: "otros",
    },
    {
      categoria: "closets",
      foto: "/assets/imgs-trabajos/closets/closet-2.jpeg",
      madera: "tzalam",
      color: "natural",
    },
    {
      categoria: "closets",
      foto: "/assets/imgs-trabajos/closets/closet-3.jpeg",
      madera: "caobilla",
      color: "oyamel",
    },
    {
      categoria: "closets",
      foto: "/assets/imgs-trabajos/closets/closet-4.jpeg",
      madera: "caobilla",
      color: "oyamel",
    },
    {
      categoria: "closets",
      foto: "/assets/imgs-trabajos/closets/closet-5.jpeg",
      madera: "caobilla",
      color: "nogal",
    },
    {
      categoria: "closets",
      foto: "/assets/imgs-trabajos/closets/closet-6.jpeg",
      madera: "caobilla",
      color: "otros",
    },
    {
      categoria: "closets",
      foto: "/assets/imgs-trabajos/closets/closet-7.jpeg",
      madera: "tzalam",
      color: "natural",
    },
    {
      categoria: "closets",
      foto: "/assets/imgs-trabajos/closets/closet-8.jpg",
      madera: "caobilla",
      color: "chocolate",
    },
    {
      categoria: "closets",
      foto: "/assets/imgs-trabajos/closets/closet-9.jpg",
      madera: "caobilla",
      color: "chocolate",
    },
    {
      categoria: "closets",
      foto: "/assets/imgs-trabajos/closets/closet-10.jpg",
      madera: "tzalam",
      color: "natural",
    },
    {
      categoria: "closets",
      foto: "/assets/imgs-trabajos/closets/closet-12.jpg",
      madera: "mdf",
      color: "otros",
    },
    {
      categoria: "closets",
      foto: "/assets/imgs-trabajos/closets/closet-13.jpg",
      madera: "caobilla",
      color: "nogal",
    },
    {
      categoria: "closets",
      foto: "/assets/imgs-trabajos/closets/closet-14.jpg",
      madera: "encino",
      color: "nogal",
    },
    {
      categoria: "closets",
      foto: "/assets/imgs-trabajos/closets/closet-15.jpg",
      madera: "mdf",
      color: "otros",
    },
    {
      categoria: "closets",
      foto: "/assets/imgs-trabajos/closets/closet-16.jpg",
      madera: "tzalam",
      color: "natural",
    },
    {
      categoria: "closets",
      foto: "/assets/imgs-trabajos/closets/closet-17.jpg",
      madera: "encino",
      color: "natural",
    },
    {
      categoria: "closets",
      foto: "/assets/imgs-trabajos/closets/closet-18.jpg",
      madera: "caobilla",
      color: "chocolate",
    },
    {
      categoria: "closets",
      foto: "/assets/imgs-trabajos/closets/closet-19.jpg",
      madera: "caobilla",
      color: "nogal",
    },
    {
      categoria: "closets",
      foto: "/assets/imgs-trabajos/closets/closet-20.jpg",
      madera: "caobilla",
      color: "cedro",
    },
    {
      categoria: "closets",
      foto: "/assets/imgs-trabajos/closets/closet-21.jpg",
      madera: "caobilla",
      color: "nogal",
    },
    {
      categoria: "closets",
      foto: "/assets/imgs-trabajos/closets/closet-22.jpg",
      madera: "mdf",
      color: "otros",
    },
    {
      categoria: "closets",
      foto: "/assets/imgs-trabajos/closets/closet-23.jpg",
      madera: "caobilla",
      color: "chocolate",
    },
    {
      categoria: "closets",
      foto: "/assets/imgs-trabajos/closets/closet-24.jpg",
      madera: "tzalam",
      color: "natural",
    },
    {
      categoria: "closets",
      foto: "/assets/imgs-trabajos/closets/closet-25.jpg",
      madera: "mdf",
      color: "otros",
    },
    {
      categoria: "closets",
      foto: "/assets/imgs-trabajos/closets/closet-26.jpg",
      madera: "caobilla",
      color: "nogal",
    },
    {
      categoria: "closets",
      foto: "/assets/imgs-trabajos/closets/closet-27.jpg",
      madera: "caobilla",
      color: "chocolate",
    },
    {
      categoria: "closets",
      foto: "/assets/imgs-trabajos/closets/closet-28.jpg",
      madera: "caobilla",
      color: "nogal",
    },
    {
      categoria: "closets",
      foto: "/assets/imgs-trabajos/closets/closet-29.jpg",
      madera: "caobilla",
      color: "cedro",
    },
    {
      categoria: "closets",
      foto: "/assets/imgs-trabajos/closets/closet-30.jpg",
      madera: "encino",
      color: "nogal",
    },
  ],
  comedores: [
    {
      categoria: "comedores",
      foto: "/assets/imgs-trabajos/comedores/comedor-1.jpg",
      madera: "tzalam",
      color: "natural",
    },
    {
      categoria: "comedores",
      foto: "/assets/imgs-trabajos/comedores/comedor-2.jpg",
      madera: "caobilla",
      color: "otro",
    },
    {
      categoria: "comedores",
      foto: "/assets/imgs-trabajos/comedores/comedor-3.jpg",
      madera: "caobilla",
      color: "chocolate",
    },
    {
      categoria: "comedores",
      foto: "/assets/imgs-trabajos/comedores/comedor-4.jpg",
      madera: "caobilla",
      color: "chocolate",
    },
    {
      categoria: "comedores",
      foto: "/assets/imgs-trabajos/comedores/comedor-5.jpeg",
      madera: "tzalam",
      color: "nogal",
    },
    {
      categoria: "comedores",
      foto: "/assets/imgs-trabajos/comedores/comedor-6.jpeg",
      madera: "tzalam",
      color: "oyamel",
    },
  ],
  tvs: [
    {
      categoria: "tvs",
      foto: "/assets/imgs-trabajos/tvs/tv-1.jpg",
      madera: "tzalam",
      color: "natural",
    },
    {
      categoria: "tvs",
      foto: "/assets/imgs-trabajos/tvs/tv-2.jpg",
      madera: "caobilla",
      color: "nogal",
    },
    {
      categoria: "tvs",
      foto: "/assets/imgs-trabajos/tvs/tv-3.jpg",
      madera: "tzalam",
      color: "natural",
    },
    {
      categoria: "tvs",
      foto: "/assets/imgs-trabajos/tvs/tv-4.jpg",
      madera: "encino",
      color: "natural",
    },
    {
      categoria: "tvs",
      foto: "/assets/imgs-trabajos/tvs/tv-5.jpeg",
      madera: "caobilla",
      color: "nogal",
    },
    {
      categoria: "tvs",
      foto: "/assets/imgs-trabajos/tvs/tv-6.jpeg",
      madera: "caobilla",
      color: "oyamel",
    },
    {
      categoria: "tvs",
      foto: "/assets/imgs-trabajos/tvs/tv-7.jpeg",
      madera: "caobilla",
      color: "blanco",
    },
  ],
  escritorios: [
    {
      categoria: "escritorios",
      foto: "/assets/imgs-trabajos/escritorios/escritorio-1.jpg",
      madera: "caobilla",
      color: "nogal",
    },
    {
      categoria: "escritorios",
      foto: "/assets/imgs-trabajos/escritorios/escritorio-2.jpg",
      madera: "caobilla",
      color: "chocolate",
    },
    {
      categoria: "escritorios",
      foto: "/assets/imgs-trabajos/escritorios/escritorio-3.jpeg",
      madera: "caobilla",
      color: "nogal",
    },
    {
      categoria: "escritorios",
      foto: "/assets/imgs-trabajos/escritorios/escritorio-4.jpeg",
      madera: "tzalam",
      color: "nogal",
    },
    {
      categoria: "escritorios",
      foto: "/assets/imgs-trabajos/escritorios/escritorio-5.jpg",
      madera: "encino",
      color: "nogal",
    },
    {
      categoria: "escritorios",
      foto: "/assets/imgs-trabajos/escritorios/escritorio-6.jpeg",
      madera: "parota",
      color: "herreria",
    },
    {
      categoria: "escritorios",
      foto: "/assets/imgs-trabajos/escritorios/escritorio-7.jpeg",
      madera: "mdf",
      color: "otros",
    },
    {
      categoria: "escritorios",
      foto: "/assets/imgs-trabajos/escritorios/escritorio-8.jpeg",
      madera: "cedro",
      color: "natural",
    },
    {
      categoria: "escritorios",
      foto: "/assets/imgs-trabajos/escritorios/escritorio-9.jpeg",
      madera: "caobilla",
      color: "nogal",
    },
  ],
  libreros: [
    {
      categoria: "libreros",
      foto: "/assets/imgs-trabajos/libreros/librero-1.jpg",
      madera: "caobilla",
      color: "otro",
    },
    {
      categoria: "libreros",
      foto: "/assets/imgs-trabajos/libreros/librero-2.jpg",
      madera: "caobilla",
      color: "cedro",
    },
    {
      categoria: "libreros",
      foto: "/assets/imgs-trabajos/libreros/librero-3.jpg",
      madera: "caobilla",
      color: "nogal",
    },
    {
      categoria: "libreros",
      foto: "/assets/imgs-trabajos/libreros/librero-4.jpg",
      madera: "caobilla",
      color: "otro",
    },
    {
      categoria: "libreros",
      foto: "/assets/imgs-trabajos/libreros/librero-5.jpg",
      madera: "caobilla",
      color: "chocolate",
    },
    {
      categoria: "libreros",
      foto: "/assets/imgs-trabajos/libreros/librero-6.jpeg",
      madera: "tzalam",
      color: "nogal",
    },
  ],
  puertas: [
    {
      categoria: "puertas",
      foto: "/assets/imgs-trabajos/puertas/puerta-1.jpg",
      madera: "cedro",
      color: "natural",
    },
    {
      categoria: "puertas",
      foto: "/assets/imgs-trabajos/puertas/puerta-2.jpg",
      madera: "caobilla",
      color: "chocolate",
    },
    {
      categoria: "puertas",
      foto: "/assets/imgs-trabajos/puertas/puerta-3.jpg",
      madera: "cedro",
      color: "otro",
    },
    {
      categoria: "puertas",
      foto: "/assets/imgs-trabajos/puertas/puerta-4.jpg",
      madera: "cedro",
      color: "nogal",
    },
    {
      categoria: "puertas",
      foto: "/assets/imgs-trabajos/puertas/puerta-5.jpg",
      madera: "caobilla",
      color: "blanco",
    },
    {
      categoria: "puertas",
      foto: "/assets/imgs-trabajos/puertas/puerta-6.jpg",
      madera: "cedro",
      color: "otro",
    },
    {
      categoria: "puertas",
      foto: "/assets/imgs-trabajos/puertas/puerta-7.jpg",
      madera: "cedro",
      color: "nogal",
    },
    {
      categoria: "puertas",
      foto: "/assets/imgs-trabajos/puertas/puerta-8.jpg",
      madera: "cedro",
      color: "nogal",
    },
    {
      categoria: "puertas",
      foto: "/assets/imgs-trabajos/puertas/puerta-9.jpg",
      madera: "tzalam",
      color: "natural",
    },
    {
      categoria: "puertas",
      foto: "/assets/imgs-trabajos/puertas/puerta-10.jpg",
      madera: "cedro",
      color: "nogal",
    },
    {
      categoria: "puertas",
      foto: "/assets/imgs-trabajos/puertas/puerta-11.jpg",
      madera: "cedro",
      color: "blanco",
    },
    {
      categoria: "puertas",
      foto: "/assets/imgs-trabajos/puertas/puerta-12.jpg",
      madera: "cedro",
      color: "natural",
    },
    {
      categoria: "puertas",
      foto: "/assets/imgs-trabajos/puertas/puerta-13.jpg",
      madera: "encino",
      color: "nogal",
    },
    {
      categoria: "puertas",
      foto: "/assets/imgs-trabajos/puertas/puerta-14.jpg",
      madera: "encino",
      color: "nogal",
    },
    {
      categoria: "puertas",
      foto: "/assets/imgs-trabajos/puertas/puerta-15.jpg",
      madera: "cedro",
      color: "nogal",
    },
    {
      categoria: "puertas",
      foto: "/assets/imgs-trabajos/puertas/puerta-16.jpg",
      madera: "cedro",
      color: "nogal",
    },
    {
      categoria: "puertas",
      foto: "/assets/imgs-trabajos/puertas/puerta-17.jpg",
      madera: "cedro",
      color: "natural",
    },
    {
      categoria: "puertas",
      foto: "/assets/imgs-trabajos/puertas/puerta-18.jpg",
      madera: "encino",
      color: "nogal",
    },
    {
      categoria: "puertas",
      foto: "/assets/imgs-trabajos/puertas/puerta-19.jpg",
      madera: "cedro",
      color: "nogal",
    },
    {
      categoria: "puertas",
      foto: "/assets/imgs-trabajos/puertas/puerta-20.jpg",
      madera: "caobilla",
      color: "otros",
    },
    {
      categoria: "puertas",
      foto: "/assets/imgs-trabajos/puertas/puerta-21.jpg",
      madera: "caobilla",
      color: "nogal",
    },
    {
      categoria: "puertas",
      foto: "/assets/imgs-trabajos/puertas/puerta-22.jpg",
      madera: "pino",
      color: "otros",
    },
    {
      categoria: "puertas",
      foto: "/assets/imgs-trabajos/puertas/puerta-23.jpg",
      madera: "cedro",
      color: "herreria",
    },
    {
      categoria: "puertas",
      foto: "/assets/imgs-trabajos/puertas/puerta-24.jpeg",
      madera: "cedro",
      color: "otros",
    },
    {
      categoria: "puertas",
      foto: "/assets/imgs-trabajos/puertas/puerta-25.jpeg",
      madera: "tzalam",
      color: "oyamel",
    },
  ],
  cocinas: [
    {
      categoria: "cocinas",
      foto: "/assets/imgs-trabajos/cocinas/cocina-1.jpg",
      madera: "caobilla",
      color: "nogal",
    },
    {
      categoria: "cocinas",
      foto: "/assets/imgs-trabajos/cocinas/cocina-2.jpg",
      madera: "tzalam",
      color: "natural",
    },
    {
      categoria: "cocinas",
      foto: "/assets/imgs-trabajos/cocinas/cocina-3.jpg",
      madera: "mdf",
      color: "naranja",
    },
    {
      categoria: "cocinas",
      foto: "/assets/imgs-trabajos/cocinas/cocina-4.jpg",
      madera: "pino",
      color: "nogal",
    },
    {
      categoria: "cocinas",
      foto: "/assets/imgs-trabajos/cocinas/cocina-5.jpg",
      madera: "mdf",
      color: "gris",
    },
    {
      categoria: "cocinas",
      foto: "/assets/imgs-trabajos/cocinas/cocina-6.jpg",
      madera: "listonado",
      color: "nogal",
    },
    {
      categoria: "cocinas",
      foto: "/assets/imgs-trabajos/cocinas/cocina-7.jpg",
      madera: "mdf",
      color: "chocolate",
    },
    {
      categoria: "cocinas",
      foto: "/assets/imgs-trabajos/cocinas/cocina-8.jpg",
      madera: "listonado",
      color: "nogal",
    },
    {
      categoria: "cocinas",
      foto: "/assets/imgs-trabajos/cocinas/cocina-9.jpg",
      madera: "listonado",
      color: "nogal",
    },
    {
      categoria: "cocinas",
      foto: "/assets/imgs-trabajos/cocinas/cocina-10.jpg",
      madera: "listonado",
      color: "oyamel",
    },
    {
      categoria: "cocinas",
      foto: "/assets/imgs-trabajos/cocinas/cocina-11.jpg",
      madera: "listonado",
      color: "nogal",
    },
    {
      categoria: "cocinas",
      foto: "/assets/imgs-trabajos/cocinas/cocina-12.jpg",
      madera: "listonado",
      color: "nogal",
    },
    {
      categoria: "cocinas",
      foto: "/assets/imgs-trabajos/cocinas/cocina-13.jpg",
      madera: "listonado",
      color: "blanco",
    },
    {
      categoria: "cocinas",
      foto: "/assets/imgs-trabajos/cocinas/cocina-14.jpg",
      madera: "listonado",
      color: "chocolate",
    },
    {
      categoria: "cocinas",
      foto: "/assets/imgs-trabajos/cocinas/cocina-15.jpg",
      madera: "listonado",
      color: "chocolate",
    },
    {
      categoria: "cocinas",
      foto: "/assets/imgs-trabajos/cocinas/cocina-16.jpg",
      madera: "listonado",
      color: "chocolate",
    },
    {
      categoria: "cocinas",
      foto: "/assets/imgs-trabajos/cocinas/cocina-17.jpg",
      madera: "pino",
      color: "natural",
    },
    {
      categoria: "cocinas",
      foto: "/assets/imgs-trabajos/cocinas/cocina-18.jpg",
      madera: "mdf",
      color: "gris",
    },
    {
      categoria: "cocinas",
      foto: "/assets/imgs-trabajos/cocinas/cocina-19.jpg",
      madera: "listonado",
      color: "nogal",
    },
    {
      categoria: "cocinas",
      foto: "/assets/imgs-trabajos/cocinas/cocina-20.jpg",
      madera: "mdf",
      color: "rojo",
    },
    {
      categoria: "cocinas",
      foto: "/assets/imgs-trabajos/cocinas/cocina-21.jpeg",
      madera: "listonado",
      color: "nogal",
    },
    {
      categoria: "cocinas",
      foto: "/assets/imgs-trabajos/cocinas/cocina-22.jpeg",
      madera: "mdf",
      color: "blanco",
    },
    {
      categoria: "cocinas",
      foto: "/assets/imgs-trabajos/cocinas/cocina-23.jpeg",
      madera: "pino",
      color: "blanco",
    },
    {
      categoria: "cocinas",
      foto: "/assets/imgs-trabajos/cocinas/cocina-24.jpeg",
      madera: "tzalam",
      color: "natural",
    },
    {
      categoria: "cocinas",
      foto: "/assets/imgs-trabajos/cocinas/cocina-24.jpeg",
      madera: "listonado",
      color: "blanco",
    },
  ],
  otros: [
    {
      categoria: "otros",
      foto: "/assets/imgs-trabajos/otros/cp-1.jpg",
      madera: "caobilla",
      color: "otros",
    },
    {
      categoria: "otros",
      foto: "/assets/imgs-trabajos/otros/cp-2.jpg",
      madera: "cedro",
      color: "natural",
    },
    {
      categoria: "otros",
      foto: "/assets/imgs-trabajos/otros/cp-3.jpg",
      madera: "cedro",
      color: "natural",
    },
    {
      categoria: "otros",
      foto: "/assets/imgs-trabajos/otros/cp-4.jpg",
      madera: "encino",
      color: "natural",
    },
    {
      categoria: "otros",
      foto: "/assets/imgs-trabajos/otros/cp-5.jpg",
      madera: "encino",
      color: "nogal",
    },
    {
      categoria: "otros",
      foto: "/assets/imgs-trabajos/otros/cp-6.jpeg",
      madera: "caobilla",
      color: "chocolate",
    },
    {
      categoria: "otros",
      foto: "/assets/imgs-trabajos/otros/cp-7.jpg",
      madera: "caobilla",
      color: "cedro",
    },
    {
      categoria: "otros",
      foto: "/assets/imgs-trabajos/otros/cp-8.jpg",
      madera: "cedro",
      color: "herreria",
    },
    {
      categoria: "otros",
      foto: "/assets/imgs-trabajos/otros/cp-9.jpeg",
      madera: "pino",
      color: "nogal",
    },
    {
      categoria: "otros",
      foto: "/assets/imgs-trabajos/otros/cp-10.jpg",
      madera: "mdf",
      color: "blanco",
    },
    {
      categoria: "otros",
      foto: "/assets/imgs-trabajos/otros/cp-11.jpg",
      madera: "pino",
      color: "blanco",
    },
    {
      categoria: "otros",
      foto: "/assets/imgs-trabajos/otros/cp-12.jpg",
      madera: "pino",
      color: "nogal",
    },
    {
      categoria: "otros",
      foto: "/assets/imgs-trabajos/otros/cp-13.jpg",
      madera: "parota",
      color: "herreria",
    },
    {
      categoria: "otros",
      foto: "/assets/imgs-trabajos/otros/cp-14.jpeg",
      madera: "pino",
      color: "otros",
    },
    {
      categoria: "otros",
      foto: "/assets/imgs-trabajos/otros/cp-15.jpeg",
      madera: "caobilla",
      color: "otros",
    },
    {
      categoria: "otros",
      foto: "/assets/imgs-trabajos/otros/cp-16.jpg",
      madera: "caobilla",
      color: "nogal",
    },
    {
      categoria: "otros",
      foto: "/assets/imgs-trabajos/otros/cp-17.jpg",
      madera: "caobilla",
      color: "nogal",
    },
    {
      categoria: "otros",
      foto: "/assets/imgs-trabajos/otros/cp-18.jpg",
      madera: "caobilla",
      color: "blanco",
    },
    {
      categoria: "otros",
      foto: "/assets/imgs-trabajos/otros/cp-19.jpg",
      madera: "caobilla",
      color: "blanco",
    },
    {
      categoria: "otros",
      foto: "/assets/imgs-trabajos/otros/cp-20.jpeg",
      madera: "parota",
      color: "natural",
    },
    {
      categoria: "otros",
      foto: "/assets/imgs-trabajos/otros/cp-21.jpg",
      madera: "zapote",
      color: "otros",
    },
    {
      categoria: "otros",
      foto: "/assets/imgs-trabajos/otros/cp-22.jpg",
      madera: "caobilla",
      color: "cedro",
    },
    {
      categoria: "otros",
      foto: "/assets/imgs-trabajos/otros/cp-23.jpg",
      madera: "caobilla",
      color: "chcolate",
    },
    {
      categoria: "otros",
      foto: "/assets/imgs-trabajos/otros/cp-24.jpeg",
      madera: "cedro",
      color: "nogal",
    },
    {
      categoria: "otros",
      foto: "/assets/imgs-trabajos/otros/cp-25.jpeg",
      madera: "tzalam",
      color: "natural",
    },
    {
      categoria: "otros",
      foto: "/assets/imgs-trabajos/otros/cp-26.jpeg",
      madera: "parota",
      color: "natural",
    },
  ],
};
